[package]
name = "register"
version = "1.3.0"
description = "A POS system for a small business"
authors = ["Rodrigo Tapia <rodrigotapia90@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }
cc = "1.1.7"

[dependencies]
tauri = { version = "1", features = [ "window-all", "dialog-all", "fs-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.24", features = ["bundled"] }
chrono = "0.4.38"
csv = "1.3.0"
cc = "1.1.7"
libc = "0.2.155"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
